[package]
name = "test"
description = "This exists purely to test complicated workflows with Knope"
publish = false
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
