[package]
versioned_files = ["Cargo.toml"]
changelog = "CHANGELOG.md"

[[package.assets]]
path = "artifact/test-x86_64-unknown-linux-musl.tgz"

[[package.assets]]
path = "artifact/test-x86_64-pc-windows-msvc.tgz"

[[package.assets]]
path = "artifact/test-x86_64-apple-darwin.tgz"

[[package.assets]]
path = "artifact/test-aarch64-apple-darwin.tgz"

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare release $version\" && git push"

[workflows.steps.variables]
"$version" = "Version"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[github]
owner = "knope-dev"
repo = "e2e-testing"
