on:
  workflow_dispatch:
    inputs:
      knope-branch:
        description: "The branch of Knope to build and test"
        default: 'main'
  push:
    branches: [main]
name: Create Release PR
jobs:
  prepare-release:
    if: "!contains(github.event.head_commit.message, 'chore: prepare release')" # Skip merges from releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Configure Git
        run: |
          git config --global user.name GitHub Actions
          git config user.email github-actions@github.com
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ github.event.inputs.knope-branch || 'main' }}
      - name: Install the latest Knope
        run: cargo install --git https://github.com/knope-dev/knope --branch ${{ github.event.inputs.knope-branch || 'main' }}
      - run: knope prepare-release --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        continue-on-error: true